### ISSUE TITLE
it doesnt work?

### ISSUE THREAD

**Issue by julesdacat** [Tuc-tac/SpotifyGeoFreedom#6]
it activated, but i still cant listen to music locked in the us (specifically one album)

also, is login the username or email?
and do i use that login then for when i get in to my account?

**Comment by julesdacat** [comment]
it just keeps it as usa

**Comment by julesdacat** [comment]
its supposed to

**Comment by julesdacat** [comment]
i was wrong

**Comment by amd64fox** [comment]
I looked at your fork, the runner works correctly and logs into the client under your account


> it activated, but i still cant listen to music locked in the us (specifically one album)

it was never mentioned that this tool unlocks music for specific regions, idk where you got that from
